name: Go

on: 
  push:
    branches: [ "master" ]

jobs:
  build-and-get:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20' # 指定所需的 Go 版本

      - name: Install dependencies
        run: go get -v ./...

      - name: Build
        run: go build -v ./...

      - name: Upload compiled binary to artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-binary # 指定生成的二进制文件的 artifact 名称
          path: ./main

      - name: Download compiled binary from artifact
        uses: actions/download-artifact@v2
        with:
          name: my-binary # 指定之前保存的构建产物名称
