name: Build RotateProxy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'  # 指定所需的 Go 版本

      - name: Download RotateProxy code
        run: git clone https://github.com/Lidong-io/rotateproxy.git ./rotateproxy

      - name: Build RotateProxy binary for Windows
        run: GOOS=windows GOARCH=amd64 go build -o rotateproxy.exe ./rotateproxy

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v2
        with:
          name: rotateproxy-artifact
          path: rotateproxy.exe
