name: Release

on:
  # 只在预发布时才执行
  release:
    types: [prereleased]

jobs:
  build:
    strategy:
      matrix:
        build: [macos, linux]
        include:
          - build: macos
            os: macos-latest
            archive-name: darwin.tar.gz
          - build: linux
            os: ubuntu-latest
            archive-name: linux.tar.gz

    # 需要设置写权限才能自动发布
    permissions:
      contents: write

    steps:
      ...
      # 把二进制文件打包成压缩文件
      - name: Prepare Packaging
        run: tar zcvf snow-${{ matrix.archive-name }}.tar.gz snow LICENSE

      # 上传附件
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: snow-${{ matrix.archive-name }}.tar.gz
          path: snow-${{ matrix.archive-name }}.tar.gz

      # 发布release版本
      - name: Release version
        uses: ncipollo/release-action@v1
        if: github.event_name == 'release'
        with:
          allowUpdates: true
          artifacts: snow-${{ matrix.archive-name }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
